### ISSUE TITLE
Cosas a mejorar

### ISSUE THREAD

**Issue by AleMinacori** [GAMS-Organization/GAMS-Repository#118]
* Validar que si la orden de trabajo no posee ningun responsable (asignada o tomada) no se pueda completar (todo desde la tabla de órdenes de trabajo) [Javi] [fix-1]
* Ordenar desde el backend en orden inverso las órdenes de trabajo y las solicitudes [Ale][fix-2]
* Revisar como se ven en mobile todas las vistas [Javi - Ale][fix-3]
* Agregar notificaciones al crear eventos en mantenimiento preventivo [Ale][fix-4]
* Agregar paginador en pagina de stock [Javi][fix-5]
* Reparar buscadores tablas herramientas, articulos [Javi][fix-6]
* Crear srcipt para levantar servidor [Ale][fix-7]
* Ordenar alfabeticamente las áreas, activos, elementos, servicios sectores [Ale][fix-8]
* Revisar modals largos [Javi][fix-9]
* Realizar teset por si las dudas [Ale][fix-10]
* * Revisar como se ven en mobile todas las vistas de los modal [Javi ][fix-11]

**Comment by AleMinacori** [comment]
Fix-2 listo

**Comment by AleMinacori** [comment]
Fix-4 listo

**Comment by AleMinacori** [comment]
Fix-7 listo

**Comment by AleMinacori** [comment]
Fix-8 listo

**Comment by javiSicardi** [comment]
fix-1 listo

**Comment by javiSicardi** [comment]
fix-5 listo

**Comment by javiSicardi** [comment]
fix-6 listo
