### ISSUE TITLE
HU 19 Notificaciones en Tiempo Real

### ISSUE THREAD

**Issue by AleMinacori** [GAMS-Organization/GAMS-Repository#21]
CÓMO usuario personal de mantenimiento - jefe 
QUIERO recibir notificaciones en tiempo real 
PARA poder conocer las actividades que están siendo solicitadas.

DADO un usuario jefe que ya ha ingresado a la aplicación 
CUANDO se registre en la aplicación alguna tarea a realizar 
ENTONCES se visualizará en una notificación la información sobre la misma.

**Comment by javiSicardi** [comment]
Notificar: 
Mantenimiento preventivo
stock
ordenes de trabajo
Solicitudes de elementos y herramientas
Backup
